INSERT INTO seasons (name, season_number, location, premiere_date, finale_date, merge_episode, status)
VALUES
    ('Survivor: 50', 50, 'Mamanuca Islands, Fiji', '2026-02-25', '2026-05-20', 7, 'ACTIVE'),
    ('Survivor: 49', 49, 'Mamanuca Islands, Fiji', '2025-09-24', '2025-12-17', 7, 'COMPLETED');
    
INSERT INTO contestants (first_name, last_name, hometown, state) VALUES
('Jenna',      'Lewis-Dougherty',   'Woodland',        'California'),
('Kyle',       'Fraser',             'Brooklyn',        'New York'),
('Savannah',   'Louie',              'Atlanta',         'Georgia'),
('Q',          'Burdette',           'Germantown',      'Tennessee'),
('Mike',       'White',              'Hanalei',         'Hawaii'),
('Angelina',   'Keeley',             'San Diego',       'California'),
('Charlie',    'Davis',              'Boston',          'Massachusetts'),
('Kamilla',    'Karthigesu',         'Foster City',     'California'),
('Genevieve',  'Mushaluk',           'Winnipeg',        'Manitoba'),
('Colby',      'Donaldson',          'Austin',          'Texas'),
('Dee',        'Valladares',         'Miami',           'Florida'),
('Chrissy',    'Hofbeck',            'The Villages',    'Florida'),
('Benjamin',   'Wade',               'Susanville',      'California'),
('Christian',  'Hubicki',            'Tallahassee',     'Florida'),
('Stephenie',  'LaGrossa Kendrick',  'Dunedin',         'Florida'),
('Emily',      'Flippen',            'Laurel',          'Maryland'),
('Oscar',      'Lusth',              'Guanajuato',      'Guanajuato'),
('Rick',       'Devens',             'Macon',           'Georgia'),
('Cirie',      'Fields',             'Jersey City',     'New Jersey'),
('Tiffany',    'Ervin',              'Los Angeles',     'California'),
('Rizo',       'Velovic',            'Yonkers',         'New York'),
('Joe',        'Hunter',             'West Sacramento', 'California'),
('Jonathan',   'Young',              'Gulf Shores',     'Alabama'),
('Aubry',      'Bracco',             'Hampton Falls',   'New Hampshire'),
('Nicole',     'Mazullo',            'Philadelphia',    'Pennsylvania'),
('Annie',      'Davis',              'Austin',          'Texas'),
('Jake',       'Latimer',            'St. Albert',      'Alberta'),
('Jeremiah',   'Ing',                'Toronto',         'Ontario'),
('Matt',       'Williams',           'St. George',      'Utah'),
('Jason',      'Treul',              'Santa Ana',       'California'),
('Shannon',    'Fairweather',        'Boston',          'Massachusetts'),
('Nate',       'Moore',              'Hermosa Beach',   'California'),
('MC',         'Chukwujekwu',        'San Diego',       'California'),
('Alex',       'Moore',              'Washington',      'District of Columbia'),
('Jawan',      'Pitts',              'Los Angeles',     'California'),
('Sophie',     'Segreti',            'New York',        'New York'),
('Steven',     'Ramm',               'Denver',          'Colorado'),
('Kristina',   'Mills',              'Edmond',          'Oklahoma'),
('Sage',       'Ahrens-Nichols',     'Olympia',         'Washington'),
('Sophi',      'Balerdi',            'Miami',           'Florida');

INSERT INTO season_contestants (season_id, contestant_id, finish_place, eliminated_episode, winner, tribe) VALUES
-- Season 50
(1,  1, 24, 1,    FALSE, 'Cila'),
(1,  2, 23, 1,    FALSE, 'Vatu'),
(1,  3, 22, 2,    FALSE, 'Cila'),
(1,  4, 21, 3,    FALSE, 'Vatu'),
(1,  5, 20, 4,    FALSE, 'Kalo'),
(1,  6, 19, 5,    FALSE, 'Vatu'),
(1,  7, 18, 5,    FALSE, 'Kalo'),
(1,  8, 17, 6,    FALSE, 'Kalo'),
(1,  9, 16, 6,    FALSE, 'Vatu'),
(1, 10, 15, 6,    FALSE, 'Vatu'),
(1, 11, 14, 7,    FALSE, 'Kalo'),
(1, 12, 13, 8,    FALSE, 'Kalo'),
(1, 13, 12, 8,    FALSE, 'Kalo'),
(1, 14, 11, 9,    FALSE, 'Cila'),
(1, 15, 10, 10,   FALSE, 'Vatu'),
(1, 16,  9, 11,   FALSE, 'Cila'),
(1, 17,  8, 11,   FALSE, 'Cila'),
(1, 18,  7, 12,   FALSE, 'Cila'),
(1, 19,  6, 12,   FALSE, 'Cila'),
(1, 20,  5, 13,   FALSE, 'Kalo'),
(1, 21,  4, 13,   FALSE, 'Vatu'),
(1, 22,  3, NULL, FALSE, 'Cila'),
(1, 23,  2, NULL, FALSE, 'Kalo'),
(1, 24,  1, NULL, TRUE, 'Vatu'),
-- Season 49
(2, 25, 18, 1,    FALSE, 'Kele'),
(2, 26, 17, 2,    FALSE, 'Kele'),
(2, 27, 16, 3,    FALSE, 'Kele'),
(2, 28, 15, 3,    FALSE, 'Kele'),
(2, 29, 14, 4,    FALSE, 'Hina'),
(2, 30, 13, 5,    FALSE, 'Hina'),
(2, 31, 12, 6,    FALSE, 'Uli'),
(2, 32, 11, 7,    FALSE, 'Uli'),
(2, 33, 10, 8,    FALSE, 'Hina'),
(2, 34,  9, 9,    FALSE, 'Kele'),
(2, 35,  8, 10,   FALSE, 'Uli'),
(2, 36,  7, 11,   FALSE, 'Hina'),
(2, 37,  6, 12,   FALSE, 'Hina'),
(2, 38,  5, 13,   FALSE, 'Hina'),
(2, 21,  4, 13,   FALSE, 'Uli'),
(2, 39,  3, NULL, FALSE, 'Uli'),
(2, 40,  2, NULL, FALSE, 'Kele'),
(2,  3,  1, NULL, TRUE, 'Uli');

UPDATE seasons SET winner_contestant_id = 24 WHERE id = 1;
UPDATE seasons SET winner_contestant_id = 3  WHERE id = 2;